spring:
  application.name: fix-engine-service
  threads.virtual.enabled: true

validation:
  clordid:
    false-positive-probability: 0.01
    expected-insertions: 1000000

tag:
  type-map: #any missing are simple String/Data types, default type
    4: CHARACTER #char
    6: FLOAT #Price
    7: POSITIVE_INTEGER #SeqNum
    9: POSITIVE_INTEGER #Length
    12: FLOAT #Amt
    13: CHARACTER #char
    14: FLOAT #Qty
    15: CURRENCY #Currency
    16: POSITIVE_INTEGER #SeqNum
    18: STRING #MultipleValueString
    20: CHARACTER #char
    21: CHARACTER #char
    24: CHARACTER #char
    25: CHARACTER #char
    28: CHARACTER #char
    29: CHARACTER #char
    30: EXCHANGE #Exchange
    31: FLOAT #Price
    32: FLOAT #Qty
    33: POSITIVE_INTEGER #NumInGroup
    34: POSITIVE_INTEGER #SeqNum
    36: POSITIVE_INTEGER #SeqNum
    38: FLOAT #Qty
    39: CHARACTER #char
    40: CHARACTER #char
    42: DATE_TIME #UTCTimestamp
    43: BOOLEAN #Boolean
    44: FLOAT #Price
    45: POSITIVE_INTEGER #SeqNum
    47: CHARACTER #char
    51: LOCAL_DATE #LocalMktDate
    52: DATE_TIME #UTCTimestamp
    53: FLOAT #Qty
    54: CHARACTER #char
    59: CHARACTER #char
    60: DATE_TIME #UTCTimestamp
    61: CHARACTER #char
    62: DATE_TIME #UTCTimestamp
    63: CHARACTER #char
    64: LOCAL_DATE #LocalMktDate
    67: INTEGER #int
    68: INTEGER #int
    71: CHARACTER #char
    73: POSITIVE_INTEGER #NumInGroup
    74: INTEGER #int
    75: LOCAL_DATE #LocalMktDate
    77: CHARACTER #char
    78: POSITIVE_INTEGER #NumInGroup
    80: FLOAT #Qty
    81: CHARACTER #char
    82: INTEGER #int
    83: INTEGER #int
    84: FLOAT #Qty
    85: POSITIVE_INTEGER #NumInGroup
    87: INTEGER #int
    88: INTEGER #int
    90: POSITIVE_INTEGER #Length
    93: POSITIVE_INTEGER #Length
    94: CHARACTER #char
    95: POSITIVE_INTEGER #Length
    97: BOOLEAN #Boolean
    98: INTEGER #int
    99: FLOAT #Price
    100: EXCHANGE #Exchange
    102: INTEGER #int
    103: INTEGER #int
    104: CHARACTER #char
    108: INTEGER #int
    110: FLOAT #Qty
    111: FLOAT #Qty
    113: BOOLEAN #Boolean
    114: BOOLEAN #Boolean
    118: FLOAT #Amt
    119: FLOAT #Amt
    120: CURRENCY #Currency
    121: BOOLEAN #Boolean
    122: DATE_TIME #UTCTimestamp
    123: BOOLEAN #Boolean
    124: POSITIVE_INTEGER #NumInGroup
    125: CHARACTER #char
    126: DATE_TIME #UTCTimestamp
    127: CHARACTER #char
    130: BOOLEAN #Boolean
    132: FLOAT #Price
    133: FLOAT #Price
    134: FLOAT #Qty
    135: FLOAT #Qty
    136: POSITIVE_INTEGER #NumInGroup
    137: FLOAT #Amt
    138: CURRENCY #Currency
    139: CHARACTER #char
    140: FLOAT #Price
    141: BOOLEAN #Boolean
    146: POSITIVE_INTEGER #NumInGroup
    150: CHARACTER #char
    151: FLOAT #Qty
    152: FLOAT #Qty
    153: FLOAT #Price
    154: FLOAT #Amt
    155: FLOAT #float
    156: CHARACTER #char
    157: INTEGER #int
    158: FLOAT #Percentage
    159: FLOAT #Amt
    160: CHARACTER #char
    163: CHARACTER #char
    165: CHARACTER #char
    168: DATE_TIME #UTCTimestamp
    169: INTEGER #int
    172: INTEGER #int
    188: FLOAT #Price
    189: FLOAT #PriceOffset
    190: FLOAT #Price
    191: FLOAT #PriceOffset
    192: FLOAT #Qty
    193: LOCAL_DATE #LocalMktDate
    194: FLOAT #Price
    195: FLOAT #PriceOffset
    197: INTEGER #int
    199: POSITIVE_INTEGER #NumInGroup
    200: MONTH_YEAR #MonthYear
    201: INTEGER #int
    202: FLOAT #Price
    203: INTEGER #int
    204: INTEGER #int
    205: DAY_OF_MONTH #DayOfMonth
    206: CHARACTER #char
    207: EXCHANGE #Exchange
    208: BOOLEAN #Boolean
    209: INTEGER #int
    210: FLOAT #Qty
    211: FLOAT #float
    212: POSITIVE_INTEGER #Length
    215: POSITIVE_INTEGER #NumInGroup
    216: INTEGER #int
    218: FLOAT #PriceOffset
    219: CHARACTER #char
    220: CURRENCY #Currency
    223: FLOAT #Percentage
    224: LOCAL_DATE #LocalMktDate
    225: LOCAL_DATE #LocalMktDate
    226: INTEGER #int
    227: FLOAT #Percentage
    228: FLOAT #float
    229: LOCAL_DATE #LocalMktDate
    230: LOCAL_DATE #LocalMktDate
    231: FLOAT #float
    232: POSITIVE_INTEGER #NumInGroup
    236: FLOAT #Percentage
    237: FLOAT #Amt
    238: FLOAT #Amt
    240: LOCAL_DATE #LocalMktDate
    241: LOCAL_DATE #LocalMktDate
    242: LOCAL_DATE #LocalMktDate
    244: INTEGER #int
    245: FLOAT #Percentage
    246: FLOAT #float
    247: LOCAL_DATE #LocalMktDate
    248: LOCAL_DATE #LocalMktDate
    249: LOCAL_DATE #LocalMktDate
    251: INTEGER #int
    252: FLOAT #Percentage
    253: FLOAT #float
    254: LOCAL_DATE #LocalMktDate
    258: BOOLEAN #Boolean
    259: LOCAL_DATE #LocalMktDate
    260: FLOAT #Price
    263: CHARACTER #char
    264: INTEGER #int
    265: INTEGER #int
    266: BOOLEAN #Boolean
    267: POSITIVE_INTEGER #NumInGroup
    268: POSITIVE_INTEGER #NumInGroup
    269: CHARACTER #char
    270: FLOAT #Price
    271: FLOAT #Qty
    272: LOCAL_DATE #UTCDateOnly
    273: TIME #UTCTimeOnly
    274: CHARACTER #char
    275: EXCHANGE #Exchange
    276: STRING #MultipleValueString
    277: STRING #MultipleValueString
    279: CHARACTER #char
    281: CHARACTER #char
    285: CHARACTER #char
    286: STRING #MultipleValueString
    287: INTEGER #int
    290: INTEGER #int
    291: STRING #MultipleValueString
    292: STRING #MultipleValueString
    293: FLOAT #Qty
    294: FLOAT #Qty
    295: POSITIVE_INTEGER #NumInGroup
    296: POSITIVE_INTEGER #NumInGroup
    297: INTEGER #int
    298: INTEGER #int
    300: INTEGER #int
    301: INTEGER #int
    303: INTEGER #int
    304: INTEGER #int
    308: EXCHANGE #Exchange
    313: MONTH_YEAR #MonthYear
    314: DAY_OF_MONTH #DayOfMonth
    315: INTEGER #int
    316: FLOAT #Price
    317: CHARACTER #char
    318: CURRENCY #Currency
    319: FLOAT #Qty
    321: INTEGER #int
    323: INTEGER #int
    325: BOOLEAN #Boolean
    326: INTEGER #int
    327: CHARACTER #char
    328: BOOLEAN #Boolean
    329: BOOLEAN #Boolean
    330: FLOAT #Qty
    331: FLOAT #Qty
    332: FLOAT #Price
    333: FLOAT #Price
    334: INTEGER #int
    338: INTEGER #int
    339: INTEGER #int
    340: INTEGER #int
    341: DATE_TIME #UTCTimestamp
    342: DATE_TIME #UTCTimestamp
    343: DATE_TIME #UTCTimestamp
    344: DATE_TIME #UTCTimestamp
    345: DATE_TIME #UTCTimestamp
    346: INTEGER #int
    348: POSITIVE_INTEGER #Length
    350: POSITIVE_INTEGER #Length
    352: POSITIVE_INTEGER #Length
    354: POSITIVE_INTEGER #Length
    356: POSITIVE_INTEGER #Length
    358: POSITIVE_INTEGER #Length
    360: POSITIVE_INTEGER #Length
    362: POSITIVE_INTEGER #Length
    364: POSITIVE_INTEGER #Length
    366: FLOAT #Price
    367: DATE_TIME #UTCTimestamp
    368: INTEGER #int
    369: POSITIVE_INTEGER #SeqNum
    370: DATE_TIME #UTCTimestamp
    371: INTEGER #int
    373: INTEGER #int
    374: CHARACTER #char
    377: BOOLEAN #Boolean
    378: INTEGER #int
    380: INTEGER #int
    381: FLOAT #Amt
    382: POSITIVE_INTEGER #NumInGroup
    383: POSITIVE_INTEGER #Length
    384: POSITIVE_INTEGER #NumInGroup
    385: CHARACTER #char
    386: POSITIVE_INTEGER #NumInGroup
    387: FLOAT #Qty
    388: CHARACTER #char
    389: FLOAT #float
    393: INTEGER #int
    394: INTEGER #int
    395: INTEGER #int
    396: FLOAT #Amt
    397: FLOAT #Amt
    398: POSITIVE_INTEGER #NumInGroup
    399: INTEGER #int
    401: INTEGER #int
    402: FLOAT #Percentage
    403: FLOAT #Percentage
    404: FLOAT #Amt
    405: FLOAT #Percentage
    406: FLOAT #Amt
    407: FLOAT #Percentage
    408: FLOAT #Amt
    409: INTEGER #int
    410: FLOAT #Percentage
    411: BOOLEAN #Boolean
    412: FLOAT #Amt
    413: FLOAT #Percentage
    414: INTEGER #int
    415: INTEGER #int
    416: INTEGER #int
    417: INTEGER #int
    418: CHARACTER #char
    419: CHARACTER #char
    420: POSITIVE_INTEGER #NumInGroup
    421: COUNTRY #Country
    422: INTEGER #int
    423: INTEGER #int
    424: FLOAT #Qty
    425: FLOAT #Qty
    426: FLOAT #Price
    427: INTEGER #int
    428: POSITIVE_INTEGER #NumInGroup
    429: INTEGER #int
    430: INTEGER #int
    431: INTEGER #int
    432: LOCAL_DATE #LocalMktDate
    433: CHARACTER #char
    434: CHARACTER #char
    435: FLOAT #Percentage
    436: FLOAT #float
    437: FLOAT #Qty
    438: DATE_TIME #UTCTimestamp
    441: INTEGER #int
    442: CHARACTER #char
    443: DATE_TIME #UTCTimestamp
    445: POSITIVE_INTEGER #Length
    447: CHARACTER #char
    449: LOCAL_DATE #UTCDateOnly
    450: TIME #UTCTimeOnly
    451: FLOAT #PriceOffset
    452: INTEGER #int
    453: POSITIVE_INTEGER #NumInGroup
    454: POSITIVE_INTEGER #NumInGroup
    457: POSITIVE_INTEGER #NumInGroup
    460: INTEGER #int
    462: INTEGER #int
    464: BOOLEAN #Boolean
    465: INTEGER #int
    468: CHARACTER #char
    469: FLOAT #float
    470: COUNTRY #Country
    473: POSITIVE_INTEGER #NumInGroup
    475: COUNTRY #Country
    477: INTEGER #int
    478: CURRENCY #Currency
    479: CURRENCY #Currency
    480: CHARACTER #char
    481: CHARACTER #char
    483: DATE_TIME #UTCTimestamp
    484: CHARACTER #char
    485: FLOAT #float
    486: LOCAL_DATE #LocalMktDate
    487: INTEGER #int
    490: LOCAL_DATE #LocalMktDate
    492: INTEGER #int
    495: INTEGER #int
    497: CHARACTER #char
    503: LOCAL_DATE #LocalMktDate
    504: LOCAL_DATE #LocalMktDate
    506: CHARACTER #char
    507: INTEGER #int
    510: POSITIVE_INTEGER #NumInGroup
    512: FLOAT #Percentage
    514: CHARACTER #char
    515: DATE_TIME #UTCTimestamp
    516: FLOAT #Percentage
    517: CHARACTER #char
    518: POSITIVE_INTEGER #NumInGroup
    519: INTEGER #int
    520: FLOAT #float
    521: CURRENCY #Currency
    522: INTEGER #int
    525: CHARACTER #char
    528: CHARACTER #char
    529: STRING #MultipleValueString
    530: CHARACTER #char
    531: CHARACTER #char
    532: CHARACTER #char
    533: INTEGER #int
    534: INTEGER #int
    537: INTEGER #int
    538: INTEGER #int
    539: POSITIVE_INTEGER #NumInGroup
    540: FLOAT #Amt
    541: LOCAL_DATE #LocalMktDate
    542: LOCAL_DATE #LocalMktDate
    544: CHARACTER #char
    546: STRING #MultipleValueString
    547: BOOLEAN #Boolean
    549: INTEGER #int
    550: INTEGER #int
    552: POSITIVE_INTEGER #NumInGroup
    555: POSITIVE_INTEGER #NumInGroup
    556: CURRENCY #Currency
    557: INTEGER #int
    558: POSITIVE_INTEGER #NumInGroup
    559: INTEGER #int
    560: INTEGER #int
    561: FLOAT #Qty
    562: FLOAT #Qty
    563: INTEGER #int
    564: CHARACTER #char
    565: INTEGER #int
    566: FLOAT #Price
    567: INTEGER #int
    569: INTEGER #int
    570: BOOLEAN #Boolean
    573: CHARACTER #char
    575: BOOLEAN #Boolean
    576: POSITIVE_INTEGER #NumInGroup
    577: INTEGER #int
    580: POSITIVE_INTEGER #NumInGroup
    581: INTEGER #int
    582: INTEGER #int
    585: INTEGER #int
    586: DATE_TIME #UTCTimestamp
    587: CHARACTER #char
    588: LOCAL_DATE #LocalMktDate
    589: CHARACTER #char
    590: CHARACTER #char
    591: CHARACTER #char
    592: COUNTRY #Country
    596: COUNTRY #Country
    604: POSITIVE_INTEGER #NumInGroup
    607: INTEGER #int
    610: MONTH_YEAR #MonthYear
    611: LOCAL_DATE #LocalMktDate
    612: FLOAT #Price
    613: CHARACTER #char
    614: FLOAT #float
    615: FLOAT #Percentage
    616: EXCHANGE #Exchange
    618: POSITIVE_INTEGER #Length
    621: POSITIVE_INTEGER #Length
    623: FLOAT #float
    624: CHARACTER #char
    626: INTEGER #int
    627: POSITIVE_INTEGER #NumInGroup
    629: DATE_TIME #UTCTimestamp
    630: POSITIVE_INTEGER #SeqNum
    631: FLOAT #Price
    632: FLOAT #Percentage
    633: FLOAT #Percentage
    634: FLOAT #Percentage
    636: BOOLEAN #Boolean
    637: FLOAT #Price
    638: INTEGER #int
    639: FLOAT #PriceOffset
    640: FLOAT #Price
    641: FLOAT #PriceOffset
    642: FLOAT #PriceOffset
    643: FLOAT #PriceOffset
    645: FLOAT #Price
    646: FLOAT #Price
    647: FLOAT #Qty
    648: FLOAT #Qty
    650: BOOLEAN #Boolean
    651: FLOAT #Price
    652: FLOAT #Qty
    653: INTEGER #int
    656: FLOAT #float
    657: FLOAT #float
    658: INTEGER #int
    660: INTEGER #int
    661: INTEGER #int
    662: FLOAT #Price
    663: INTEGER #int
    665: INTEGER #int
    666: INTEGER #int
    667: MONTH_YEAR #MonthYear
    668: INTEGER #int
    669: FLOAT #Price
    670: POSITIVE_INTEGER #NumInGroup
    673: FLOAT #Qty
    675: CURRENCY #Currency
    676: CURRENCY #Currency
    679: FLOAT #Price
    680: INTEGER #int
    681: FLOAT #Price
    683: POSITIVE_INTEGER #NumInGroup
    684: FLOAT #Price
    685: FLOAT #Qty
    686: INTEGER #int
    687: FLOAT #Qty
    690: INTEGER #int
    692: INTEGER #int
    694: INTEGER #int
    695: CHARACTER #char
    696: LOCAL_DATE #LocalMktDate
    697: FLOAT #Price
    698: INTEGER #int
    700: BOOLEAN #Boolean
    701: LOCAL_DATE #LocalMktDate
    702: POSITIVE_INTEGER #NumInGroup
    704: FLOAT #Qty
    705: FLOAT #Qty
    706: INTEGER #int
    708: FLOAT #Amt
    709: INTEGER #int
    711: POSITIVE_INTEGER #NumInGroup
    712: INTEGER #int
    715: LOCAL_DATE #LocalMktDate
    718: INTEGER #int
    719: BOOLEAN #Boolean
    720: BOOLEAN #Boolean
    722: INTEGER #int
    723: INTEGER #int
    724: INTEGER #int
    725: INTEGER #int
    727: INTEGER #int
    728: INTEGER #int
    729: INTEGER #int
    730: FLOAT #Price
    731: INTEGER #int
    732: FLOAT #Price
    733: INTEGER #int
    734: FLOAT #Price
    735: POSITIVE_INTEGER #NumInGroup
    736: CURRENCY #Currency
    737: FLOAT #Amt
    738: FLOAT #Amt
    739: LOCAL_DATE #LocalMktDate
    741: FLOAT #Amt
    742: FLOAT #Amt
    743: LOCAL_DATE #LocalMktDate
    744: CHARACTER #char
    745: FLOAT #Qty
    746: FLOAT #Amt
    747: CHARACTER #char
    748: INTEGER #int
    749: INTEGER #int
    750: INTEGER #int
    751: INTEGER #int
    752: INTEGER #int
    753: POSITIVE_INTEGER #NumInGroup
    754: BOOLEAN #Boolean
    756: POSITIVE_INTEGER #NumInGroup
    757: STRING #String
    758: CHARACTER #char
    759: INTEGER #int
    765: FLOAT #Percentage
    766: FLOAT #Amt
    767: CURRENCY #Currency
    768: POSITIVE_INTEGER #NumInGroup
    769: DATE_TIME #UTCTimestamp
    770: INTEGER #int
    773: INTEGER #int
    774: INTEGER #int
    775: INTEGER #int
    776: INTEGER #int
    778: POSITIVE_INTEGER #NumInGroup
    779: DATE_TIME #UTCTimestamp
    780: INTEGER #int
    781: POSITIVE_INTEGER #NumInGroup
    783: CHARACTER #char
    784: INTEGER #int
    786: INTEGER #int
    787: CHARACTER #char
    788: INTEGER #int
    789: POSITIVE_INTEGER #SeqNum
    792: INTEGER #int
    794: INTEGER #int
    796: INTEGER #int
    797: BOOLEAN #Boolean
    798: INTEGER #int
    799: FLOAT #Price
    800: FLOAT #Qty
    801: POSITIVE_INTEGER #NumInGroup
    802: POSITIVE_INTEGER #NumInGroup
    803: INTEGER #int
    804: POSITIVE_INTEGER #NumInGroup
    805: INTEGER #int
    806: POSITIVE_INTEGER #NumInGroup
    807: INTEGER #int
    808: INTEGER #int
    810: FLOAT #Price
    811: FLOAT #float
    812: INTEGER #int
    813: INTEGER #int
    814: INTEGER #int
    815: INTEGER #int
    816: POSITIVE_INTEGER #NumInGroup
    819: INTEGER #int
    826: INTEGER #int
    827: INTEGER #int
    828: INTEGER #int
    829: INTEGER #int
    832: INTEGER #int
    834: FLOAT #PriceOffset
    835: INTEGER #int
    836: INTEGER #int
    837: INTEGER #int
    838: INTEGER #int
    839: FLOAT #Price
    840: INTEGER #int
    841: INTEGER #int
    842: INTEGER #int
    843: INTEGER #int
    844: INTEGER #int
    845: FLOAT #Price
    846: INTEGER #int
    847: INTEGER #int
    849: FLOAT #Percentage
    850: FLOAT #float
    851: INTEGER #int
    852: BOOLEAN #Boolean
    853: INTEGER #int
    854: INTEGER #int
    855: INTEGER #int
    856: INTEGER #int
    857: INTEGER #int
    858: FLOAT #Amt
    860: FLOAT #Price
    861: FLOAT #Price
    862: POSITIVE_INTEGER #NumInGroup
    863: FLOAT #Qty
    864: POSITIVE_INTEGER #NumInGroup
    865: INTEGER #int
    866: LOCAL_DATE #LocalMktDate
    867: FLOAT #Price
    869: FLOAT #Percentage
    870: POSITIVE_INTEGER #NumInGroup
    871: INTEGER #int
    873: LOCAL_DATE #LocalMktDate
    874: LOCAL_DATE #LocalMktDate
    875: INTEGER #int
    879: FLOAT #Qty
    882: FLOAT #Price
    883: FLOAT #Price
    884: FLOAT #Amt
    885: FLOAT #Amt
    886: FLOAT #Amt
    887: POSITIVE_INTEGER #NumInGroup
    890: FLOAT #Amt
    891: INTEGER #int
    892: INTEGER #int
    893: BOOLEAN #Boolean
    895: INTEGER #int
    896: INTEGER #int
    897: POSITIVE_INTEGER #NumInGroup
    898: FLOAT #Percentage
    899: FLOAT #Amt
    900: FLOAT #Amt
    901: FLOAT #Amt
    903: INTEGER #int
    905: INTEGER #int
    906: INTEGER #int
    910: INTEGER #int
    911: INTEGER #int
    912: BOOLEAN #Boolean
    915: LOCAL_DATE #LocalMktDate
    916: LOCAL_DATE #LocalMktDate
    917: LOCAL_DATE #LocalMktDate
    918: CURRENCY #Currency
    919: INTEGER #int
    920: FLOAT #Amt
    921: FLOAT #Amt
    922: FLOAT #Amt
    924: INTEGER #int
    926: INTEGER #int
    928: INTEGER #int
    935: INTEGER #int
    936: POSITIVE_INTEGER #NumInGroup
    937: INTEGER #int
    938: POSITIVE_INTEGER #NumInGroup
    939: INTEGER #int
    940: INTEGER #int
    941: CURRENCY #Currency
    942: CURRENCY #Currency
    944: INTEGER #int
    945: INTEGER #int
    946: INTEGER #int
    947: CURRENCY #Currency
    948: POSITIVE_INTEGER #NumInGroup
    950: CHARACTER #char
    951: INTEGER #int
    952: POSITIVE_INTEGER #NumInGroup
    954: INTEGER #int
    955: MONTH_YEAR #MonthYear
    956: LOCAL_DATE #LocalMktDate